on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/cargo-build-publish.yml@b2acaf7bd30189e15392baed5d5b3e06ef78158b # main
    secrets:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
